import Link from "next/link";
import { redirect } from "next/navigation";
import { getSessionUser } from "@/lib/auth";
import { isAdmin } from "@/lib/admin";
import { analyticsRange,getAdminAnalytics } from "@/lib/analytics";

export const metadata={title:"Mr.ME administration",robots:{index:false,follow:false}};
export const dynamic="force-dynamic";

export default async function AdminDashboard(){
 const user=await getSessionUser();if(!user)redirect("/login?next=/admin");if(!isAdmin(user))redirect("/unauthorized");
 const {from,to}=analyticsRange(30),data=await getAdminAnalytics(from,to),paid=data.statuses.find(x=>x.status==="PAID")?._count._all??0,pending=data.statuses.find(x=>x.status==="PENDING")?._count._all??0,failed=data.statuses.filter(x=>["FAILED","EXPIRED","CANCELLED"].includes(x.status)).reduce((sum,x)=>sum+x._count._all,0);
 return <section className="container-pad pt-28 pb-24"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Mr.ME administration</p><h1 className="mt-3 text-3xl font-semibold">Operations overview</h1><p className="mt-2 text-sm text-white/45">Real PostgreSQL metrics. Revenue includes only confirmed payments and remains separated by currency.</p></div><nav className="flex flex-wrap gap-2">{[["Products","/admin/products"],["Customers","/admin/customers"],["Sales","/admin/sales"],["Coupons","/admin/coupons"],["Audit logs","/admin/audit-logs"]].map(([label,href])=><Link key={href} href={href} className="rounded-xl border border-white/10 px-4 py-2 text-sm hover:border-violet-400/40">{label}</Link>)}</nav></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Customers" value={data.totalCustomers}/><Kpi label="New today" value={data.newToday}/><Kpi label="New this month" value={data.newMonth}/><Kpi label="Verified customers" value={data.verified}/><Kpi label="Suspended customers" value={data.suspended}/><Kpi label="Successful purchases · 30d" value={paid}/><Kpi label="Pending payments · 30d" value={pending}/><Kpi label="Failed/expired · 30d" value={failed}/><Kpi label="Active products" value={data.activeProducts}/><Kpi label="Active sessions" value={data.activeSessions}/><Kpi label="Coupon redemptions · 30d" value={data.coupons}/>{data.revenue.map(item=><Kpi key={item.currency} label={`Confirmed revenue · ${item.currency}`} value={(item.total/100).toFixed(2)}/>)}</div><div className="mt-10 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 p-6"><h2 className="text-lg font-semibold">Revenue by day</h2><div className="mt-5 space-y-3">{data.revenueByDay.map(point=><div key={`${point.day}-${point.currency}`} className="flex justify-between border-b border-white/[.07] pb-2 text-sm"><span>{new Date(point.day).toLocaleDateString()}</span><span>{(point.amount/100).toFixed(2)} {point.currency} · {point.orders} orders</span></div>)}{!data.revenueByDay.length&&<p className="text-sm text-white/40">No confirmed revenue in this period.</p>}</div></div><div className="rounded-2xl border border-white/10 p-6"><h2 className="text-lg font-semibold">Top-selling products</h2><div className="mt-5 space-y-3">{data.topProducts.map(item=><div key={item.courseId} className="flex justify-between border-b border-white/[.07] pb-2 text-sm"><span>{item.titleEn}</span><span>{item.count} sales</span></div>)}{!data.topProducts.length&&<p className="text-sm text-white/40">No confirmed product sales.</p>}</div></div></div></section>;
}
function Kpi({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs text-white/40">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>}
