import { test,expect } from "@playwright/test";
import { PrismaClient } from "@prisma/client";
const email=()=>`student-${Date.now()}-${Math.floor(Math.random()*10000)}@example.test`;
async function login(page:import("@playwright/test").Page,address="enrolled@example.test"){await page.goto("/login");await page.getByLabel("Email address").fill(address);await page.locator('input[name="password"]').fill("SecurePass123");await page.getByRole("button",{name:"Sign in"}).click();await expect(page).toHaveURL(/dashboard/)}
test("public course library is visible",async({page})=>{await page.goto("/courses");await expect(page.getByRole("heading",{name:/Build your complete/})).toBeVisible()});
test("protected routes redirect anonymous users",async({page})=>{await page.goto("/dashboard");await expect(page).toHaveURL(/\/login\?next=/)});
test("student is denied direct admin access",async({page})=>{await login(page);await page.goto("/admin");await expect(page).toHaveURL(/unauthorized/)});
test("email registration rejects invalid code then verifies",async({page})=>{const address=email();await page.goto("/register");await page.getByLabel("Full name").fill("Test Student");await page.getByLabel("Email address").fill(address);await page.locator('input[name="password"]').fill("SecurePass123");await page.getByLabel("Confirm password").fill("SecurePass123");await page.getByRole("checkbox").check();await page.getByRole("button",{name:"Send verification code"}).click();await expect(page).toHaveURL(/verify-email/);expect((await page.request.post("/api/auth/login",{data:{email:address,password:"SecurePass123"}})).status()).toBe(403);await page.getByLabel("Verification code").fill("111111");await page.getByRole("button",{name:"Verify email"}).click();await expect(page.getByText(/Invalid or expired/)).toBeVisible();await page.getByLabel("Verification code").fill("246810");await page.getByRole("button",{name:"Verify email"}).click();await expect(page).toHaveURL(/dashboard/)});
test("verified email login and logout",async({page})=>{await login(page);await page.getByRole("button",{name:"Sign out"}).click();await expect(page).toHaveURL("/")});
test("contact form submits",async({page})=>{await page.goto("/contact");await page.getByLabel("Name").fill("Test Student");await page.getByLabel("Email").fill("student@example.test");await page.getByLabel("Message").fill("This is a deterministic integration test message.");await page.getByRole("button",{name:"Send message"}).click();await expect(page.getByText("Message received.")).toBeVisible()});
test("student cannot request admin upload",async({page})=>{await login(page);const response=await page.request.post("/api/admin/lessons/pa-1/video",{data:{maxDurationSeconds:3600}});expect(response.status()).toBe(403)});
test("public registration cannot assign an admin role",async({page})=>{const response=await page.request.post("/api/auth/register",{data:{name:"Bad Actor",email:email(),password:"SecurePass123",passwordConfirmation:"SecurePass123",termsAccepted:true,role:"ADMIN"}});expect(response.status()).toBe(400)});
test("admin can open database-backed dashboard",async({page})=>{await login(page,"admin@example.test");await page.goto("/admin");await expect(page.getByRole("heading",{name:"Academy operations"})).toBeVisible();await expect(page.getByText("admin@example.test").first()).toBeVisible()});
test("checkout rejects invalid course identifiers",async({page})=>{await login(page);const response=await page.request.post("/api/purchase",{data:{courseIds:["nonexistent-course"]}});expect(response.status()).toBe(400)});
test("enrolled user receives signed playback and refund revokes access",async({page})=>{await login(page);let response=await page.request.post("/api/lessons/pa-1/playback");expect(response.status()).toBe(200);const body=await response.json();expect(body.playback.token).toContain("test-");expect(body.playback.watermark).toContain("@");const db=new PrismaClient();await db.purchase.update({where:{providerSessionId:"e2e-paid"},data:{status:"REFUNDED"}});await db.$disconnect();response=await page.request.post("/api/lessons/pa-1/playback");expect(response.status()).toBe(404)});
