import { test,expect } from "@playwright/test";
async function login(page:import("@playwright/test").Page,address="enrolled@example.test"){await page.goto("/login");await page.getByLabel("Email address").fill(address);await page.locator('input[name="password"]').fill("SecurePass123");await page.getByRole("button",{name:"Sign in"}).click();await expect(page).toHaveURL(/dashboard/)}
test("English and Arabic directions persist",async({page,context})=>{await page.goto("/");await expect(page.locator("html")).toHaveAttribute("dir","ltr");await context.addCookies([{name:"mrm_locale",value:"ar",domain:"127.0.0.1",path:"/"}]);await page.reload();await expect(page.locator("html")).toHaveAttribute("lang","ar");await expect(page.locator("html")).toHaveAttribute("dir","rtl")});
test("protected routes redirect anonymous users",async({page})=>{await page.goto("/dashboard");await expect(page).toHaveURL(/\/login\?next=/)});
test("student is denied direct admin access",async({page})=>{await login(page);await page.goto("/admin");await expect(page).toHaveURL(/unauthorized/)});
test("paid owner can open purchase access page",async({page})=>{await login(page);await page.goto("/dashboard");await page.getByText("Open access").first().click();await expect(page.getByText("Payment confirmed")).toBeVisible();await expect(page.getByRole("link",{name:"Join Telegram"})).toBeVisible()});
test("public course APIs never disclose Telegram destinations",async({request})=>{for(const path of ["/api/courses","/api/courses/e2e-private-access"]){const response=await request.get(path),body=await response.text();expect(body).not.toContain("telegramAccessUrl");expect(body).not.toContain("t.me/")}});
test("removed video routes return 404",async({request})=>{expect((await request.post("/api/lessons/pa-1/playback")).status()).toBe(404);expect((await request.post("/api/webhooks/cloudflare-stream")).status()).toBe(404);expect((await request.post("/api/admin/lessons/pa-1/video")).status()).toBe(404)});
test("public registration cannot assign an admin role",async({request})=>{const response=await request.post("/api/auth/register",{data:{name:"Bad Actor",email:`actor-${Date.now()}@example.test`,password:"SecurePass123",passwordConfirmation:"SecurePass123",termsAccepted:true,role:"ADMIN"}});expect(response.status()).toBe(400)});
test("admin can open database-backed dashboard",async({page})=>{await login(page,"admin@example.test");await page.goto("/admin");await expect(page.getByRole("heading",{name:"Operations overview"})).toBeVisible()});
