import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { getSessionUser } from "@/lib/auth";
import { isAdmin } from "@/lib/admin";
import { buildPurchaseTimeline,getAdminPurchaseDiagnostics } from "@/lib/admin-purchases";
import { AdminReconcileButton,AdminRevokeGrantButton } from "@/components/admin-purchase-actions";
import { StatusBadge } from "@/components/ui";

export const metadata={title:"Purchase diagnostics",robots:{index:false,follow:false}};
export const dynamic="force-dynamic";
const shown=(value:unknown)=>value===null||value===undefined||value===""?"—":String(value);
const money=(cents:number,currency:string)=>`${(cents/100).toFixed(2)} ${currency}`;
export default async function PurchaseDiagnostics({params}:{params:Promise<{purchaseId:string}>}){
 const purchaseId=(await params).purchaseId,actor=await getSessionUser();if(!actor)redirect(`/login?next=/admin/sales/${encodeURIComponent(purchaseId)}`);if(!isAdmin(actor))redirect("/unauthorized");
 const diagnostics=await getAdminPurchaseDiagnostics(purchaseId);if(!diagnostics)notFound();const {purchase}=diagnostics,timeline=buildPurchaseTimeline(diagnostics),enrolled=new Set(purchase.enrollments.map(item=>item.courseId));
 const canReconcile=purchase.provider==="nowpayments"&&Boolean(purchase.providerPaymentId)&&["PENDING","EXPIRED"].includes(purchase.status);
 return <section className="container-pad pt-28 pb-24"><Link href="/admin/sales" className="text-sm text-white/45 hover:text-white">← Back to purchase support</Link><div className="mt-7 flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow">Purchase diagnostics</p><h1 className="mt-3 break-all font-mono text-2xl font-semibold">{purchase.id}</h1><p className="mt-2 text-sm text-white/45">Safe operational data only. Provider payloads, credentials, webhook hashes, and invite URLs are excluded.</p></div><StatusBadge status={purchase.providerStatus==="partially_paid"?"PARTIALLY PAID":purchase.status}/></div>{canReconcile&&<div className="mt-7 rounded-2xl border border-violet-400/20 bg-violet-500/[.06] p-5"><AdminReconcileButton purchaseId={purchase.id}/></div>}
 <div className="mt-8 grid gap-6 xl:grid-cols-2"><Panel title="Customer"><Field label="Name" value={purchase.user.name}/><Field label="Email" value={purchase.user.email}/><Field label="User ID" value={purchase.user.id} mono muted/></Panel><Panel title="Order"><Field label="Original" value={money(purchase.originalAmountCents,purchase.currency)}/><Field label="Discount" value={money(purchase.discountAmountCents,purchase.currency)}/><Field label="Final" value={money(purchase.amountCents,purchase.currency)}/><Field label="Coupon" value={purchase.coupon?.code}/><Field label="Coupon state" value={purchase.couponRedemption?.status}/>{purchase.items.map(item=><Field key={item.courseId} label={item.course.titleEn} value={`${money(item.priceCents,purchase.currency)} · ${item.course.slug}`}/>)}</Panel>
 <Panel title="Payment"><Field label="Internal status" value={purchase.status}/><Field label="Provider status" value={purchase.providerStatus}/><Field label="Provider" value={purchase.provider}/><Field label="Provider payment ID" value={purchase.providerPaymentId} mono/><Field label="Expected USDT" value={purchase.expectedAmount?.toString()}/><Field label="Received USDT" value={purchase.receivedAmount?.toString()}/><Field label="Pay currency" value={purchase.payCurrency}/><Field label="Network" value={purchase.network}/><Field label="Payment address" value={purchase.paymentAddress} mono/><Field label="Transaction hash" value={purchase.transactionHash} mono/><Field label="Created" value={purchase.createdAt.toLocaleString()}/><Field label="Paid" value={purchase.paidAt?.toLocaleString()}/><Field label="Expires" value={purchase.expiresAt?.toLocaleString()}/></Panel>
 <Panel title="Reconciliation"><Field label="Last attempted" value={purchase.lastReconciledAt?.toLocaleString()}/><Field label="Next eligible" value={purchase.nextReconcileAt?.toLocaleString()}/><Field label="Attempts" value={purchase.reconcileAttempts}/><Field label="Safe error code" value={purchase.reconciliationErrorCode}/><p className="mt-4 text-xs leading-5 text-white/40">Reconciliation queries NOWPayments through the validated provider and canonical payment transition path. It cannot accept payment data from this page.</p></Panel>
 <Panel title="Entitlement">{purchase.items.map(item=>{const exists=enrolled.has(item.courseId),reason=exists?"Enrollment exists":purchase.status==="REFUNDED"?"Enrollment removed after refund":purchase.status!=="PAID"?"Payment not complete":"Enrollment missing — investigate canonical fulfillment";return <div key={item.courseId} className="border-b border-white/[.07] py-3"><div className="flex items-center justify-between gap-4"><span>{item.course.titleEn}</span><StatusBadge status={exists?"ACTIVE":"NOT ENROLLED"}/></div><p className="mt-1 text-xs text-white/45">{reason} · Course {item.course.status}</p></div>})}</Panel>
 <Panel title="Telegram fulfillment">{purchase.items.map(item=><div key={item.courseId} className="border-b border-white/[.07] py-3"><p className="font-medium">{item.course.titleEn}</p><p className="mt-1 text-xs text-white/45">Course access {item.course.telegramAccessEnabled?"enabled":"disabled"} · Chat ID {item.course.telegramChatId?"configured":"missing"}</p></div>)}{purchase.accessGrants.map(grant=><div key={grant.id} className="mt-4 rounded-xl border border-white/10 bg-black/15 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><span className="font-mono text-xs text-white/55">{grant.id}</span><StatusBadge status={grant.status}/></div><div className="mt-3 grid gap-1 text-xs text-white/45 sm:grid-cols-2"><span>Course: {grant.course.titleEn}</span><span>Created: {grant.createdAt.toLocaleString()}</span><span>Expires: {grant.expiresAt.toLocaleString()}</span><span>Redeemed: {grant.redeemedAt?.toLocaleString()??"—"}</span><span>Revoked: {grant.revokedAt?.toLocaleString()??"—"}</span><span>Failure: {grant.lastErrorCode??"—"}</span></div>{["ACTIVE","PENDING"].includes(grant.status)&&<div className="mt-4"><AdminRevokeGrantButton grantId={grant.id}/></div>}</div>)}{!purchase.accessGrants.length&&<p className="mt-3 text-sm text-white/40">Not requested.</p>}</Panel>
 {purchase.status==="REFUNDED"&&<Panel title="Refund diagnostics"><Field label="Refunded at" value={purchase.refundedAt?.toLocaleString()}/><Field label="Refunded amount" value={money(purchase.refundedAmountCents,purchase.currency)}/><Field label="Provider reference" value={purchase.refundReference}/><p className="mt-4 rounded-xl border border-amber-400/20 bg-amber-500/10 p-3 text-sm text-amber-100">Refund externally / provider action required. This admin interface does not initiate refunds.</p></Panel>}</div>
 <div className="mt-8 rounded-2xl border border-white/10 p-6"><h2 className="text-lg font-semibold">Operational timeline</h2><p className="mt-1 text-xs text-white/40">Built only from persisted Purchase, transaction, webhook, Enrollment, grant, and audit records.</p><ol className="mt-5 space-y-4">{timeline.map(event=><li key={event.id} className="grid gap-1 border-s border-violet-400/30 ps-4 sm:grid-cols-[12rem_1fr]"><time className="text-xs text-white/40">{event.at.toLocaleString()}</time><div><p className="text-sm font-medium">{event.title}</p><p className="mt-1 break-all text-xs text-white/40">{event.detail}</p></div></li>)}</ol></div></section>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><h2 className="text-lg font-semibold">{title}</h2><div className="mt-4">{children}</div></section>}
function Field({label,value,mono=false,muted=false}:{label:string;value:unknown;mono?:boolean;muted?:boolean}){return <div className="grid gap-1 border-b border-white/[.07] py-2.5 sm:grid-cols-[10rem_1fr]"><p className="text-xs text-white/40">{label}</p><p className={`${mono?"break-all font-mono text-xs":"text-sm"} ${muted?"text-white/40":"text-white/75"}`}>{shown(value)}</p></div>}
