import { randomUUID } from "node:crypto";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { db } from "@/lib/db";
import { createReservedPurchase } from "@/lib/coupons";
const suffix=randomUUID(),admin=`coupon-admin-${suffix}`,user1=`coupon-u1-${suffix}`,user2=`coupon-u2-${suffix}`,course=`coupon-course-${suffix}`;
beforeAll(async()=>{await db.user.createMany({data:[admin,user1,user2].map((id,index)=>({id,name:id,email:`${id}@example.test`,normalizedEmail:`${id}@example.test`,passwordHash:"x",role:index===0?"ADMIN" as const:"STUDENT" as const}))});await db.course.create({data:{id:course,slug:course,titleEn:"Coupon course",titleAr:"دورة الخصم",shortDescriptionEn:"Coupon",shortDescriptionAr:"خصم",fullDescriptionEn:"Coupon course",fullDescriptionAr:"دورة خصم",instructor:"Mr.ME",priceCents:10000,currency:"USD",image:"https://example.test/image.jpg",accent:"#000",telegramAccessUrl:"https://t.me/test",status:"PUBLISHED",publishedAt:new Date()}})});
afterAll(async()=>{await db.couponRedemption.deleteMany({where:{userId:{in:[user1,user2]}}});await db.purchase.deleteMany({where:{userId:{in:[user1,user2]}}});await db.coupon.deleteMany({where:{createdByUserId:admin}});await db.course.delete({where:{id:course}});await db.user.deleteMany({where:{id:{in:[admin,user1,user2]}}});await db.$disconnect()});
describe("coupon reservations",()=>{
 it("applies server-calculated percentage discount",async()=>{await db.coupon.create({data:{code:`P25-${suffix}`,normalizedCode:`P25-${suffix}`.toUpperCase(),descriptionEn:"25 percent",descriptionAr:"خصم",discountType:"PERCENTAGE",discountValue:25,active:true,createdByUserId:admin,products:{create:{courseId:course}}}});const purchase=await createReservedPurchase({userId:user1,courseIds:[course],couponCode:`p25-${suffix}`,provider:"test"});expect(purchase.originalAmountCents).toBe(10000);expect(purchase.discountAmountCents).toBe(2500);expect(purchase.amountCents).toBe(7500)});
 it("does not exceed a concurrent global usage limit",async()=>{await db.coupon.create({data:{code:`ONE-${suffix}`,normalizedCode:`ONE-${suffix}`.toUpperCase(),descriptionEn:"One use",descriptionAr:"استخدام واحد",discountType:"FIXED_AMOUNT",discountValue:1000,currency:"USD",active:true,totalUsageLimit:1,createdByUserId:admin,products:{create:{courseId:course}}}});const results=await Promise.allSettled([createReservedPurchase({userId:user1,courseIds:[course],couponCode:`ONE-${suffix}`,provider:"test"}),createReservedPurchase({userId:user2,courseIds:[course],couponCode:`ONE-${suffix}`,provider:"test"})]);expect(results.filter(x=>x.status==="fulfilled")).toHaveLength(1)});
});
