import { randomUUID } from "node:crypto";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { db } from "@/lib/db";
import { processPaymentEvent } from "@/lib/payment";
const suffix=randomUUID(),userId=`test-user-${suffix}`,courseId=`test-course-${suffix}`;
beforeAll(async()=>{const email=`payment-${suffix}@example.test`;await db.user.create({data:{id:userId,name:"Payment Test",email,normalizedEmail:email,emailVerifiedAt:new Date(),status:"ACTIVE",passwordHash:"x"}});await db.course.create({data:{id:courseId,slug:`test-${suffix}`,title:"Test",eyebrow:"Test",description:"Test",longDescription:"Test",instructor:"Test",difficulty:"Beginner",duration:"1h",lessonCount:0,priceCents:1000,rating:0,reviewCount:0,image:"https://example.test/x.jpg",accent:"#000000",outcomes:[],requirements:[],status:"PUBLISHED",publishedAt:new Date()}})});
afterAll(async()=>{await db.playbackSession.deleteMany({where:{userId}});await db.enrollment.deleteMany({where:{userId}});await db.purchase.deleteMany({where:{userId}});await db.course.delete({where:{id:courseId}});await db.user.delete({where:{id:userId}});await db.$disconnect()});
async function purchase(id:string,expected:string){return db.purchase.create({data:{id,userId,provider:"nowpayments",providerSessionId:`session-${id}`,providerPaymentId:`provider-${id}`,status:"PENDING",amountCents:1000,currency:"USD",expectedAmount:expected,payCurrency:"usdttrc20",network:"TRC20",items:{create:{courseId,priceCents:1000}}}})}
describe("payment enrollment transaction",()=>{
 it("grants enrollment exactly once after a verified fully-paid event",async()=>{const value=await purchase(`paid-${suffix}`,"10");const event={eventId:`event-${suffix}`,purchaseId:value.id,providerPaymentId:`provider-${value.id}`,status:"PAID" as const,providerStatus:"finished",receivedAmount:"10",payCurrency:"usdttrc20",network:"TRC20",raw:{}};expect((await processPaymentEvent("nowpayments",event,"paid-payload")).duplicate).toBe(false);expect(await db.enrollment.count({where:{userId,courseId}})).toBe(1);expect((await processPaymentEvent("nowpayments",event,"paid-payload")).duplicate).toBe(true);expect(await db.enrollment.count({where:{userId,courseId}})).toBe(1)});
 it("does not enroll an underpayment",async()=>{await db.enrollment.deleteMany({where:{userId,courseId}});const value=await purchase(`under-${suffix}`,"10");await processPaymentEvent("nowpayments",{eventId:`under-event-${suffix}`,purchaseId:value.id,providerPaymentId:`provider-${value.id}`,status:"PAID",providerStatus:"partially_paid",receivedAmount:"9.99",payCurrency:"usdttrc20",network:"TRC20",raw:{}},"under-payload");expect((await db.purchase.findUniqueOrThrow({where:{id:value.id}})).status).toBe("PENDING");expect(await db.enrollment.count({where:{userId,courseId}})).toBe(0)});
 it("rejects an invalid network",async()=>{const value=await purchase(`network-${suffix}`,"10");await expect(processPaymentEvent("nowpayments",{eventId:`network-event-${suffix}`,purchaseId:value.id,providerPaymentId:`provider-${value.id}`,status:"PAID",providerStatus:"finished",receivedAmount:"10",payCurrency:"usdteth",network:"ERC20",raw:{}},"network-payload")).rejects.toThrow("Invalid settlement asset")});
});
