import { randomUUID } from "node:crypto";
import { afterAll,beforeAll,beforeEach,describe,expect,it } from "vitest";
import { db } from "@/lib/db";
import { processPaymentEvent,type VerifiedPaymentEvent } from "@/lib/payment";

const suffix=randomUUID(),userId=`test-user-${suffix}`,courseId=`test-course-${suffix}`;
beforeAll(async()=>{const email=`payment-${suffix}@example.test`;await db.user.create({data:{id:userId,name:"Payment Test",email,normalizedEmail:email,emailVerifiedAt:new Date(),status:"ACTIVE",passwordHash:"x"}});await db.course.create({data:{id:courseId,slug:`test-${suffix}`,titleEn:"Test",titleAr:"اختبار",shortDescriptionEn:"Test product description",shortDescriptionAr:"وصف منتج اختباري",fullDescriptionEn:"Complete test product description.",fullDescriptionAr:"وصف كامل للمنتج الاختباري.",instructor:"Test",priceCents:1000,image:"https://example.test/x.jpg",accent:"#000000",telegramAccessUrl:"https://t.me/test",status:"PUBLISHED",publishedAt:new Date()}})});
beforeEach(async()=>{await db.courseAccessGrant.deleteMany({where:{userId}});await db.enrollment.deleteMany({where:{userId}})});
afterAll(async()=>{await db.courseAccessGrant.deleteMany({where:{userId}});await db.enrollment.deleteMany({where:{userId}});await db.purchase.deleteMany({where:{userId}});await db.course.delete({where:{id:courseId}});await db.user.delete({where:{id:userId}});await db.$disconnect()});

async function purchase(label:string,expected="10",status:"PENDING"|"EXPIRED"="PENDING"){const id=`${label}-${randomUUID()}`;return db.purchase.create({data:{id,userId,provider:"nowpayments",providerSessionId:`session-${id}`,providerPaymentId:`provider-${id}`,status,amountCents:1000,currency:"USD",expectedAmount:expected,payCurrency:"usdttrc20",network:"TRC20",paymentAddress:`address-${id}`,items:{create:{courseId,priceCents:1000}}}})}
function event(value:Awaited<ReturnType<typeof purchase>>,overrides:Partial<VerifiedPaymentEvent>={}):VerifiedPaymentEvent{return {eventId:`event-${randomUUID()}`,purchaseId:value.id,providerPaymentId:`provider-${value.id}`,status:"PAID",providerStatus:"finished",expectedAmount:"10",receivedAmount:"10",payCurrency:"usdttrc20",network:"TRC20",paymentAddress:`address-${value.id}`,priceAmount:"10",priceCurrency:"USD",raw:{},...overrides}}

describe("payment enrollment transaction",()=>{
 it("grants a full payment once and records one transition",async()=>{const value=await purchase("paid"),payment=event(value);expect((await processPaymentEvent("nowpayments",payment,"paid-payload")).duplicate).toBe(false);expect((await db.purchase.findUniqueOrThrow({where:{id:value.id}})).status).toBe("PAID");expect(await db.enrollment.count({where:{userId,courseId}})).toBe(1);expect((await processPaymentEvent("nowpayments",payment,"paid-payload")).duplicate).toBe(true);expect(await db.enrollment.count({where:{userId,courseId}})).toBe(1);expect(await db.paymentTransaction.count({where:{eventId:payment.eventId}})).toBe(1)});
 it("keeps a partial payment pending without rounding",async()=>{const value=await purchase("partial");await processPaymentEvent("nowpayments",event(value,{receivedAmount:"9.999999"}),"partial-payload");expect((await db.purchase.findUniqueOrThrow({where:{id:value.id}})).status).toBe("PENDING");expect(await db.enrollment.count({where:{userId,courseId}})).toBe(0)});
 it("accepts an overpayment",async()=>{const value=await purchase("over");await processPaymentEvent("nowpayments",event(value,{receivedAmount:"10.000001"}),"over-payload");expect((await db.purchase.findUniqueOrThrow({where:{id:value.id}})).status).toBe("PAID");expect(await db.enrollment.count({where:{userId,courseId}})).toBe(1)});
 it("rejects replayed event IDs with a different payload",async()=>{const value=await purchase("replay"),payment=event(value);await processPaymentEvent("nowpayments",payment,"original-payload");await expect(processPaymentEvent("nowpayments",payment,"changed-payload")).rejects.toThrow("Webhook replay payload mismatch")});
 it.each([
  ["wrong payment ID",{providerPaymentId:"other"},"Purchase binding mismatch"],
  ["wrong purchase binding",{purchaseId:"other"},"Purchase binding mismatch"],
  ["wrong provider",{},"Purchase binding mismatch"],
  ["wrong network",{network:"ERC20"},"Invalid settlement asset"],
  ["wrong currency",{payCurrency:"usdteth"},"Invalid settlement asset"],
  ["wrong expected amount",{expectedAmount:"11"},"Purchase settlement terms mismatch"],
  ["wrong payment address",{paymentAddress:"other"},"Purchase settlement terms mismatch"],
  ["wrong fiat binding",{priceAmount:"9",priceCurrency:"EUR"},"Purchase settlement terms mismatch"],
 ] as const)("rejects %s",async(label,overrides,message)=>{const value=await purchase("binding");await expect(processPaymentEvent(label==="wrong provider"?"other":"nowpayments",event(value,overrides),`payload-${randomUUID()}`)).rejects.toThrow(message)});
 it("handles expiry and a later independently verified final payment",async()=>{const value=await purchase("late");await processPaymentEvent("nowpayments",event(value,{status:"EXPIRED",providerStatus:"expired",receivedAmount:"0"}),"expired-payload");expect((await db.purchase.findUniqueOrThrow({where:{id:value.id}})).status).toBe("EXPIRED");await processPaymentEvent("nowpayments",event(value),"late-finished-payload");expect((await db.purchase.findUniqueOrThrow({where:{id:value.id}})).status).toBe("PAID");expect(await db.enrollment.count({where:{userId,courseId}})).toBe(1)});
 it("records failed payment without granting access",async()=>{const value=await purchase("failed");await processPaymentEvent("nowpayments",event(value,{status:"FAILED",providerStatus:"failed",receivedAmount:"0"}),"failed-payload");expect((await db.purchase.findUniqueOrThrow({where:{id:value.id}})).status).toBe("FAILED");expect(await db.enrollment.count({where:{userId,courseId}})).toBe(0)});
 it("revokes the enrollment and outstanding access grants on refund and cannot re-grant them",async()=>{const value=await purchase("refund");await processPaymentEvent("nowpayments",event(value),"refund-paid-payload");const enrollment=await db.enrollment.findUniqueOrThrow({where:{userId_courseId:{userId,courseId}}});await db.courseAccessGrant.create({data:{userId,courseId,purchaseId:value.id,enrollmentId:enrollment.id,status:"ACTIVE",expiresAt:new Date(Date.now()+15*60_000),externalInviteId:"safe-name"}});await processPaymentEvent("nowpayments",event(value,{status:"REFUNDED",providerStatus:"refunded"}),"refund-payload");expect((await db.purchase.findUniqueOrThrow({where:{id:value.id}})).status).toBe("REFUNDED");expect(await db.enrollment.count({where:{userId,courseId}})).toBe(0);expect((await db.courseAccessGrant.findFirstOrThrow({where:{purchaseId:value.id}})).status).toBe("REVOKED");await expect(processPaymentEvent("nowpayments",event(value),"post-refund-payload")).rejects.toThrow("Invalid payment transition");expect(await db.enrollment.count({where:{userId,courseId}})).toBe(0)});
});
