import { randomUUID } from "node:crypto";
import { afterAll,beforeAll,beforeEach,describe,expect,it,vi } from "vitest";
import { db } from "@/lib/db";
import { issueCourseAccess } from "@/lib/telegram-access";
import { TelegramClientError,type TelegramAccessProvider } from "@/lib/providers/telegram";
import { courseRepository } from "@/lib/course-repository";

const suffix=randomUUID(),owner=`owner-${suffix}`,other=`other-${suffix}`,courseId=`product-${suffix}`,paid=`paid-${suffix}`,pending=`pending-${suffix}`;
const inviteUrl="https://t.me/+temporary-test-invite";
const provider:TelegramAccessProvider={createInvite:vi.fn(async input=>({inviteUrl,expiresAt:input.expiresAt,memberLimit:input.memberLimit,name:input.name})),revokeInvite:vi.fn(async()=>undefined),checkChat:vi.fn(async()=>undefined)};

beforeAll(async()=>{
 await db.user.createMany({data:[owner,other].map(id=>({id,name:"Test",email:`${id}@example.test`,normalizedEmail:`${id}@example.test`,passwordHash:"x",emailVerifiedAt:new Date(),status:"ACTIVE" as const}))});
 await db.course.create({data:{id:courseId,slug:courseId,titleEn:"Access",titleAr:"الوصول",shortDescriptionEn:"Private product access",shortDescriptionAr:"وصول خاص للمنتج",fullDescriptionEn:"Private product access description.",fullDescriptionAr:"وصف كامل للوصول الخاص.",instructor:"Mr.ME",priceCents:1000,image:"https://example.test/x.jpg",accent:"#3B82F6",telegramAccessUrl:"https://t.me/legacy_must_not_be_used",telegramChatId:"-1001234567890",telegramAccessEnabled:true,status:"PUBLISHED",publishedAt:new Date()}});
 for(const [id,status] of [[paid,"PAID"],[pending,"PENDING"]] as const)await db.purchase.create({data:{id,userId:owner,provider:"fixture",providerSessionId:`session-${id}`,status,amountCents:1000,currency:"USD",items:{create:{courseId,priceCents:1000}}}});
 await db.enrollment.create({data:{userId:owner,courseId,purchaseId:paid}});
});
beforeEach(async()=>{await db.courseAccessGrant.deleteMany({where:{courseId}});vi.mocked(provider.createInvite).mockReset().mockImplementation(async input=>({inviteUrl,expiresAt:input.expiresAt,memberLimit:input.memberLimit,name:input.name}));vi.mocked(provider.revokeInvite).mockReset().mockResolvedValue(undefined);await db.purchase.update({where:{id:paid},data:{status:"PAID"}});await db.enrollment.upsert({where:{userId_courseId:{userId:owner,courseId}},create:{userId:owner,courseId,purchaseId:paid},update:{purchaseId:paid}});await db.course.update({where:{id:courseId},data:{telegramAccessEnabled:true,telegramChatId:"-1001234567890",status:"PUBLISHED",publishedAt:new Date()}})});
afterAll(async()=>{await db.courseAccessGrant.deleteMany({where:{courseId}});await db.enrollment.deleteMany({where:{courseId}});await db.purchase.deleteMany({where:{userId:owner}});await db.course.delete({where:{id:courseId}});await db.user.deleteMany({where:{id:{in:[owner,other]}}});await db.$disconnect()});

async function denied(action:()=>Promise<unknown>,code:string){await expect(action()).rejects.toMatchObject({name:"CourseAccessError",code})}

describe("secure Telegram course fulfillment",()=>{
 it("creates a short one-member invite for the exact enrolled user's server-configured chat",async()=>{const now=new Date("2030-01-01T00:00:00.000Z"),result=await issueCourseAccess(owner,courseId,{enabled:true,provider,now});expect(result.inviteUrl).toBe(inviteUrl);expect(provider.createInvite).toHaveBeenCalledWith(expect.objectContaining({chatId:"-1001234567890",memberLimit:1,expiresAt:new Date("2030-01-01T00:15:00.000Z")}));expect((await db.courseAccessGrant.findFirstOrThrow({where:{courseId}}))).toMatchObject({userId:owner,purchaseId:paid,status:"ACTIVE"});expect((await db.securityAuditLog.findFirstOrThrow({where:{action:"COURSE_ACCESS_GRANTED",entityId:result.grantId}})).metadata).not.toHaveProperty("inviteUrl")});
 it("denies an absent or wrong user's Enrollment",async()=>{await denied(()=>issueCourseAccess(other,courseId,{enabled:true,provider}),"ENTITLEMENT_REQUIRED");await db.enrollment.delete({where:{userId_courseId:{userId:owner,courseId}}});await denied(()=>issueCourseAccess(owner,courseId,{enabled:true,provider}),"ENTITLEMENT_REQUIRED");expect(provider.createInvite).not.toHaveBeenCalled()});
 it("denies an Enrollment whose associated Purchase is not PAID",async()=>{await db.enrollment.update({where:{userId_courseId:{userId:owner,courseId}},data:{purchaseId:pending}});await denied(()=>issueCourseAccess(owner,courseId,{enabled:true,provider}),"ENTITLEMENT_REQUIRED");expect(provider.createInvite).not.toHaveBeenCalled()});
 it("denies a refunded Purchase and a revoked Enrollment",async()=>{await db.purchase.update({where:{id:paid},data:{status:"REFUNDED"}});await denied(()=>issueCourseAccess(owner,courseId,{enabled:true,provider}),"ENTITLEMENT_REQUIRED");await db.purchase.update({where:{id:paid},data:{status:"PAID"}});await db.enrollment.delete({where:{userId_courseId:{userId:owner,courseId}}});await denied(()=>issueCourseAccess(owner,courseId,{enabled:true,provider}),"ENTITLEMENT_REQUIRED")});
 it("fails closed when globally or locally disabled",async()=>{await denied(()=>issueCourseAccess(owner,courseId,{enabled:false,provider}),"ACCESS_DISABLED");await db.course.update({where:{id:courseId},data:{telegramAccessEnabled:false}});await denied(()=>issueCourseAccess(owner,courseId,{enabled:true,provider}),"ACCESS_DISABLED");expect(provider.createInvite).not.toHaveBeenCalled()});
 it("enforces three attempts per user/course/hour",async()=>{const now=new Date("2030-01-01T00:00:00.000Z");for(let count=0;count<3;count++)await issueCourseAccess(owner,courseId,{enabled:true,provider,now:new Date(now.getTime()+count)});await denied(()=>issueCourseAccess(owner,courseId,{enabled:true,provider,now:new Date(now.getTime()+3)}),"RATE_LIMITED");expect(provider.createInvite).toHaveBeenCalledTimes(3)},30_000);
 it("serializes concurrent in-flight requests",async()=>{let release!:(value:{inviteUrl:string;expiresAt:Date;memberLimit:number;name:string})=>void;vi.mocked(provider.createInvite).mockImplementationOnce(input=>new Promise(resolve=>{release=value=>resolve(value);void input}));const first=issueCourseAccess(owner,courseId,{enabled:true,provider});await vi.waitFor(()=>expect(provider.createInvite).toHaveBeenCalledTimes(1),{timeout:15_000,interval:100});const second=issueCourseAccess(owner,courseId,{enabled:true,provider});await denied(()=>second,"ISSUANCE_IN_PROGRESS");const call=vi.mocked(provider.createInvite).mock.calls[0][0];release({inviteUrl,expiresAt:call.expiresAt,memberLimit:1,name:call.name});await expect(first).resolves.toMatchObject({inviteUrl});expect(provider.createInvite).toHaveBeenCalledTimes(1)},30_000);
 it("records safe failed metadata without changing Enrollment or Purchase",async()=>{vi.mocked(provider.createInvite).mockRejectedValueOnce(new TelegramClientError("TIMEOUT"));await denied(()=>issueCourseAccess(owner,courseId,{enabled:true,provider}),"TELEGRAM_UNAVAILABLE");expect((await db.courseAccessGrant.findFirstOrThrow({where:{courseId}}))).toMatchObject({status:"FAILED",lastErrorCode:"TIMEOUT"});expect((await db.purchase.findUniqueOrThrow({where:{id:paid}})).status).toBe("PAID");expect(await db.enrollment.count({where:{userId:owner,courseId}})).toBe(1)});
 it("never uses the legacy permanent URL",async()=>{const result=await issueCourseAccess(owner,courseId,{enabled:true,provider});expect(result.inviteUrl).not.toContain("legacy_must_not_be_used");expect(JSON.stringify(await db.courseAccessGrant.findMany({where:{courseId}}))).not.toContain(inviteUrl)});
 it("keeps legacy URLs and server chat configuration out of customer course data",async()=>{const customer=JSON.stringify(await courseRepository.getBySlug(courseId));expect(customer).not.toMatch(/telegramAccessUrl|telegramChatId|legacy_must_not_be_used|-1001234567890/)});
});
