"use client";
import { useState } from "react";
import { Button,Spinner } from "@/components/ui";
export default function ForgotPage(){
 const [step,setStep]=useState<"request"|"confirm"|"done">("request"),[email,setEmail]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function requestCode(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setMessage("");const data=new FormData(event.currentTarget),value=String(data.get("email")).trim().toLowerCase();try{await fetch("/api/auth/password-reset",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:value})});setEmail(value);setStep("confirm");setMessage("If the email is eligible, a reset code has been sent.")}catch{setMessage("The service is temporarily unavailable.")}finally{setBusy(false)}}
 async function confirm(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setMessage("");const data=new FormData(event.currentTarget);try{const response=await fetch("/api/auth/password-reset/confirm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,code:data.get("code"),newPassword:data.get("newPassword"),passwordConfirmation:data.get("passwordConfirmation")})});if(!response.ok)throw new Error();setStep("done");setMessage("Password changed. All previous sessions were revoked.")}catch{setMessage("The reset code or password is invalid or expired.")}finally{setBusy(false)}}
 return <section className="container-pad flex min-h-[720px] items-center justify-center pt-20"><div className="w-full max-w-md"><p className="eyebrow">Account recovery</p><h1 className="mt-3 text-3xl font-semibold">{step==="request"?"Reset your password.":step==="confirm"?"Enter your reset code.":"Password updated."}</h1>{step==="request"&&<form onSubmit={requestCode} className="mt-8 space-y-4"><label className="block text-xs text-white/45">Email address<input name="email" type="email" autoComplete="email" inputMode="email" required className="input mt-2"/></label><Button type="submit" disabled={busy} className="w-full">{busy&&<Spinner/>}Send reset code</Button></form>}{step==="confirm"&&<form onSubmit={confirm} className="mt-8 space-y-4"><input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required className="input text-center tracking-[.3em]" placeholder="000000"/><input name="newPassword" type="password" autoComplete="new-password" minLength={10} required className="input" placeholder="New password"/><input name="passwordConfirmation" type="password" autoComplete="new-password" minLength={10} required className="input" placeholder="Confirm new password"/><Button type="submit" disabled={busy} className="w-full">{busy&&<Spinner/>}Change password</Button></form>}<div aria-live="polite">{message&&<p className="mt-4 text-sm text-white/60">{message}</p>}</div>{step==="done"&&<Button href="/login" className="mt-6 w-full">Sign in</Button>}</div></section>
}
