"use client";
import { useState } from "react";
import Image from "next/image";
import { Check, ChevronDown, Clock3, Layers3, Play, ShieldCheck, Star } from "lucide-react";
import type { Course } from "@/lib/types";
import { Button } from "@/components/ui";
import { formatPrice } from "@/lib/utils";

export function CourseDetail({ course }: { course: Course }) {
  const [open, setOpen] = useState(0);
  return <><section className="border-b border-white/[.06] pt-28 pb-16"><div className="container-pad grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="eyebrow">{course.eyebrow}</p><h1 className="mt-5 text-balance text-4xl font-semibold tracking-[-.04em] sm:text-6xl">{course.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/55">{course.longDescription}</p><div className="mt-7 flex flex-wrap gap-5 text-sm text-white/50"><span className="flex items-center gap-1.5 text-amber-300"><Star className="h-4 w-4 fill-current"/>{course.rating} <span className="text-white/35">({course.reviews} reviews)</span></span><span className="flex gap-1.5"><Clock3 className="h-4 w-4"/>{course.duration}</span><span className="flex gap-1.5"><Layers3 className="h-4 w-4"/>{course.lessons} lessons</span></div><p className="mt-5 text-sm text-white/40">Taught by <span className="text-white">{course.instructor}</span></p></div><div className="glass overflow-hidden rounded-3xl p-3"><div className="relative aspect-video overflow-hidden rounded-2xl"><Image src={course.image} alt="" fill priority className="object-cover"/><div className="absolute inset-0 bg-black/25"/><button aria-label="Play course preview" className="absolute left-1/2 top-1/2 flex h-16 w-16 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-white/30 bg-white/15 backdrop-blur-md transition hover:scale-105 hover:bg-blue-600"><Play className="ml-1 h-5 w-5 fill-current"/></button></div><div className="flex items-center justify-between p-5"><div><p className="text-xs text-white/35">Full lifetime access</p><p className="mt-1 text-3xl font-semibold">{formatPrice(course.price)}</p></div><Button href="/register" className="px-7">Enroll now</Button></div><div className="flex items-center gap-2 border-t border-white/[.07] px-5 pt-4 pb-2 text-xs text-white/40"><ShieldCheck className="h-4 w-4 text-emerald-400"/>Secure checkout · 14-day satisfaction guarantee</div></div></div></section>
  <section className="container-pad grid gap-14 py-20 lg:grid-cols-[1fr_.38fr]"><div><h2 className="text-2xl font-semibold">What you&apos;ll learn</h2><div className="mt-7 grid gap-4 sm:grid-cols-2">{course.outcomes.map(x=><div key={x} className="flex gap-3 text-sm text-white/65"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-blue-500/15"><Check className="h-3 w-3 text-blue-400"/></span>{x}</div>)}</div><h2 className="mt-16 text-2xl font-semibold">Course curriculum</h2><div className="mt-6 overflow-hidden rounded-2xl border border-white/[.09]">{course.curriculum.map((module,i)=><div key={module.title} className="border-b border-white/[.07] last:border-0"><button onClick={()=>setOpen(open===i?-1:i)} className="flex w-full items-center justify-between bg-white/[.025] p-5 text-left"><span><span className="text-[10px] uppercase tracking-widest text-blue-400">Module {i+1}</span><span className="mt-1 block font-medium">{module.title}</span></span><ChevronDown className={`h-4 w-4 transition ${open===i?"rotate-180":""}`}/></button>{open===i&&<div className="divide-y divide-white/[.06]">{module.lessons.map((lesson,j)=><div key={lesson.id} className="flex items-center justify-between px-5 py-4 text-sm"><span className="flex items-center gap-3 text-white/60"><span className="text-xs text-white/25">{String(j+1).padStart(2,"0")}</span>{lesson.title}{lesson.preview&&<span className="rounded bg-blue-500/10 px-2 py-0.5 text-[10px] text-blue-300">Preview</span>}</span><span className="text-xs text-white/30">{lesson.duration}</span></div>)}</div>}</div>)}</div></div><aside><div className="sticky top-24 rounded-2xl border border-white/[.09] bg-white/[.03] p-6"><h3 className="font-semibold">Requirements</h3><ul className="mt-5 space-y-3">{course.requirements.map(x=><li key={x} className="flex gap-2 text-sm leading-6 text-white/45"><Check className="mt-1 h-3.5 w-3.5 shrink-0 text-blue-400"/>{x}</li>)}</ul><div className="mt-7 border-t border-white/[.08] pt-6"><p className="text-xs uppercase tracking-wider text-white/30">This course includes</p><div className="mt-4 space-y-3 text-sm text-white/50"><p>{course.duration} on-demand video</p><p>{course.lessons} guided lessons</p><p>Downloadable resources</p><p>Certificate of completion</p><p>Lifetime access</p></div></div></div></aside></section></>;
}
