"use client";
import { useState } from "react";
import Link from "next/link";
import { Check,ChevronLeft,ChevronRight,Play } from "lucide-react";
import type { Course } from "@/lib/types";
export function VideoPlayer({course}:{course:Course}){
 const lessons=course.curriculum.flatMap(module=>module.lessons),[active,setActive]=useState(0),[done,setDone]=useState<string[]>([]),[notes,setNotes]=useState(""),[playback,setPlayback]=useState<{iframeUrl:string;watermark:string}|null>(null),[error,setError]=useState("");
 const lesson=lessons[active];
 async function startPlayback(){setError("");const response=await fetch(`/api/lessons/${lesson.id}/playback`,{method:"POST"});const body=await response.json();if(!response.ok){setError(body.error?.message??"Playback unavailable");return}setPlayback(body.playback)}
 async function toggleComplete(){const completed=!done.includes(lesson.id),response=await fetch("/api/progress",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({lessonId:lesson.id,positionSec:0,completed})});if(response.ok)setDone(value=>completed?[...new Set([...value,lesson.id])]:value.filter(id=>id!==lesson.id))}
 async function saveNotes(){await fetch("/api/notes",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({lessonId:lesson.id,body:notes})})}
 function changeLesson(index:number){setActive(index);setPlayback(null);setError("");setNotes("")}
 return <div className="min-h-screen bg-[#08080b]"><header className="flex h-16 items-center justify-between border-b border-white/[.08] px-6"><Link href="/dashboard" className="flex items-center gap-2 text-sm text-white/50"><ChevronLeft className="h-4 w-4"/>Dashboard</Link><p>{course.title}</p><span className="text-xs text-white/30">{active+1} / {lessons.length}</span></header><div className="grid lg:grid-cols-[1fr_340px]"><main>
  <div className="relative flex aspect-video max-h-[70vh] items-center justify-center bg-black">{playback?<><iframe src={playback.iframeUrl} allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture" allowFullScreen className="h-full w-full border-0" title={lesson.title}/><div className="pointer-events-none absolute right-5 top-5 rounded bg-black/45 px-3 py-2 text-xs text-white/60">{playback.watermark}</div></>:<button onClick={startPlayback} className="flex h-20 w-20 items-center justify-center rounded-full bg-white text-black"><Play className="ml-1 h-6 w-6 fill-current"/></button>}{error&&<p className="absolute bottom-6 rounded-lg bg-red-500/15 px-4 py-2 text-sm text-red-300">{error}</p>}</div>
  <div className="p-8"><p className="eyebrow">Lesson {active+1}</p><h1 className="mt-2 text-2xl font-semibold">{lesson.title}</h1><div className="mt-6 flex gap-3"><button onClick={toggleComplete} className="rounded-xl border border-white/10 px-4 py-2 text-sm"><Check className="mr-2 inline h-4 w-4"/>Mark complete</button><button disabled={active===0} onClick={()=>changeLesson(active-1)} className="rounded-xl border border-white/10 px-4 disabled:opacity-30"><ChevronLeft className="inline h-4 w-4"/> Previous</button><button disabled={active===lessons.length-1} onClick={()=>changeLesson(active+1)} className="rounded-xl bg-blue-600 px-4 disabled:opacity-30">Next <ChevronRight className="inline h-4 w-4"/></button></div><h2 className="mt-10 font-medium">Lesson notes</h2><textarea value={notes} onChange={event=>setNotes(event.target.value)} onBlur={saveNotes} className="input mt-3 h-32 resize-none py-3"/></div>
 </main><aside className="border-l border-white/[.08] bg-white/[.02]"><div className="p-5"><h2>Course content</h2><p className="mt-1 text-xs text-white/35">{done.length} of {lessons.length} complete</p></div>{lessons.map((item,index)=><button key={item.id} onClick={()=>changeLesson(index)} className={`flex w-full gap-3 border-t border-white/[.06] p-4 text-left text-sm ${index===active?"bg-blue-500/10":""}`}><span>{done.includes(item.id)?"✓":index+1}</span>{item.title}</button>)}</aside></div></div>;
}
