import Link from "next/link";
import { redirect } from "next/navigation";
import { getSessionUser } from "@/lib/auth";
import { isAdmin } from "@/lib/admin";
import { db } from "@/lib/db";

export const metadata={title:"Customers",robots:{index:false,follow:false}};
export const dynamic="force-dynamic";
export default async function Customers({searchParams}:{searchParams:Promise<{search?:string;status?:string;page?:string}>}){
 const actor=await getSessionUser();if(!actor)redirect("/login?next=/admin/customers");if(!isAdmin(actor))redirect("/unauthorized");const query=await searchParams,page=Math.max(1,Number(query.page??1)||1),take=25,search=(query.search??"").slice(0,100);
 const allowed=["PENDING_VERIFICATION","ACTIVE","DISABLED","SUSPENDED","DELETION_PENDING","DELETED","MIGRATION_REQUIRED"] as const,status=allowed.find(x=>x===query.status);
 const where={...(status?{status}:{}),...(search?{OR:[{name:{contains:search,mode:"insensitive" as const}},{normalizedEmail:{contains:search,mode:"insensitive" as const}}]}:{})};
 const [users,total]=await db.$transaction([db.user.findMany({where,select:{id:true,name:true,email:true,emailVerifiedAt:true,status:true,preferredLanguage:true,createdAt:true,lastLoginAt:true,_count:{select:{purchases:true}}},orderBy:{createdAt:"desc"},skip:(page-1)*take,take}),db.user.count({where})]);
 const ids=users.map(x=>x.id),[spend,sessions]=await Promise.all([db.purchase.groupBy({by:["userId","currency"],where:{userId:{in:ids},status:"PAID"},_sum:{amountCents:true}}),db.session.groupBy({by:["userId"],where:{userId:{in:ids},revokedAt:null,expiresAt:{gt:new Date()}},_count:{_all:true}})]);
 return <section className="container-pad pt-28 pb-24"><p className="eyebrow">Customers</p><h1 className="mt-3 text-3xl font-semibold">Customer management</h1><form className="mt-6 flex flex-wrap gap-3"><input name="search" defaultValue={search} className="input max-w-sm" placeholder="Name or email"/><select name="status" defaultValue={status} className="input max-w-xs"><option value="">All statuses</option>{allowed.map(x=><option key={x}>{x}</option>)}</select><button className="rounded-xl bg-blue-600 px-5">Filter</button></form><p className="mt-4 text-sm text-white/40">{total} customers</p><div className="mt-6 overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-full text-sm"><thead><tr>{["Customer","Verified","Status","Language","Registered","Last login","Purchases","Paid","Sessions"].map(x=><th key={x} className="px-4 py-3 text-start text-white/45">{x}</th>)}</tr></thead><tbody>{users.map(user=><tr key={user.id} className="border-t border-white/10"><td className="px-4 py-3"><Link className="text-blue-300" href={`/admin/customers/${user.id}`}>{user.name}</Link><p className="text-xs text-white/40">{user.email}</p></td><td className="px-4 py-3">{user.emailVerifiedAt?"Yes":"No"}</td><td className="px-4 py-3">{user.status}</td><td className="px-4 py-3">{user.preferredLanguage}</td><td className="px-4 py-3">{user.createdAt.toLocaleDateString()}</td><td className="px-4 py-3">{user.lastLoginAt?.toLocaleString()??"Never"}</td><td className="px-4 py-3">{user._count.purchases}</td><td className="px-4 py-3">{spend.filter(x=>x.userId===user.id).map(x=>`${((x._sum.amountCents??0)/100).toFixed(2)} ${x.currency}`).join(", ")||"0"}</td><td className="px-4 py-3">{sessions.find(x=>x.userId===user.id)?._count._all??0}</td></tr>)}</tbody></table></div></section>;
}
