import { Check, Crown, Sparkles } from "lucide-react";
import { Button, SectionHeading } from "@/components/ui";

const plans = [
  { name:"Single course", price:"From $199", copy:"Go deep on one specific skill.", features:["Lifetime course access","All future course updates","Completion certificate","Student community"], cta:"Explore courses", href:"/courses" },
  { name:"Complete bundle", price:"$649", old:"$827", copy:"The full Mr.M trading curriculum.", features:["All three premium courses","Lifetime access to every course","Future bundle course additions","Priority community support","All certificates"], cta:"Get complete access", href:"/register", featured:true },
  { name:"Team access", price:"Custom", copy:"Trading teams and private groups.", features:["Five or more seats","Centralized billing","Progress reporting","Private onboarding"], cta:"Contact us", href:"/contact" }
];
export default function PricingPage() {
  return <div className="pt-16"><section className="bg-grid bg-[size:56px_56px] py-20 text-center sm:py-28"><div className="container-pad"><SectionHeading eyebrow="Simple pricing" title="Invest in skill that stays with you." copy="One payment. No recurring subscription. Learn at your pace with lifetime access." align="center"/></div></section><section className="container-pad pb-24"><div className="grid gap-6 lg:grid-cols-3">{plans.map(p=><div key={p.name} className={`relative rounded-3xl border p-7 ${p.featured?"border-blue-400/40 bg-blue-500/[.08] shadow-glow":"border-white/[.09] bg-white/[.03]"}`}>{p.featured&&<span className="absolute right-5 top-5 flex items-center gap-1 rounded-full bg-blue-600 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider"><Sparkles className="h-3 w-3"/>Best value</span>}<div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/[.07]">{p.featured?<Crown className="h-5 w-5 text-blue-400"/>:<Sparkles className="h-5 w-5 text-white/50"/>}</div><h2 className="mt-6 text-xl font-semibold">{p.name}</h2><p className="mt-2 text-sm text-white/45">{p.copy}</p><div className="mt-7 flex items-end gap-2"><span className="text-4xl font-semibold tracking-tight">{p.price}</span>{p.old&&<span className="pb-1 text-sm text-white/30 line-through">{p.old}</span>}</div><Button href={p.href} variant={p.featured?"primary":"secondary"} className="mt-7 w-full">{p.cta}</Button><ul className="mt-7 space-y-4 border-t border-white/[.08] pt-7">{p.features.map(f=><li key={f} className="flex gap-2.5 text-sm text-white/55"><Check className="h-4 w-4 text-blue-400"/>{f}</li>)}</ul></div>)}</div><div className="mt-16 overflow-x-auto rounded-2xl border border-white/[.09]"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-white/[.04]"><tr><th className="p-5">Included</th><th>Single</th><th>Bundle</th><th>Team</th></tr></thead><tbody className="divide-y divide-white/[.07] text-white/50">{[["Lifetime access","Yes","Yes","Yes"],["Certificates","1","All","All"],["Future courses","—","Included","Optional"],["Priority support","—","Yes","Yes"],["Progress reporting","—","—","Yes"]].map(row=><tr key={row[0]}>{row.map((x,i)=><td key={x+i} className={`p-5 ${i===0?"text-white":""}`}>{x}</td>)}</tr>)}</tbody></table></div></section></div>;
}
