// @vitest-environment jsdom
import React from "react";
import "@testing-library/jest-dom/vitest";
import { cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import { CourseAccessButton } from "@/components/course-access-button";

beforeEach(()=>vi.stubGlobal("fetch",vi.fn()));
afterEach(()=>{cleanup();vi.unstubAllGlobals()});
const success=()=>new Response(JSON.stringify({grant:{inviteUrl:"https://t.me/+temporary-invite",expiresAt:"2030-01-01T00:15:00.000Z"}}),{status:200,headers:{"Content-Type":"application/json"}});

describe("My Courses secure access UX",()=>{
 it("renders no Telegram destination before an authenticated access request",()=>{const {container}=render(<CourseAccessButton courseSlug="secure-course" locale="en"/>);expect(screen.getByRole("button",{name:"Access Course"})).toBeInTheDocument();expect(container.innerHTML).not.toMatch(/t\.me|telegramAccessUrl|bot.?token/i)});
 it("disables duplicate clicks while preparing and then exposes only the temporary invite",async()=>{let finish!:(response:Response)=>void;vi.mocked(fetch).mockReturnValue(new Promise(resolve=>{finish=resolve}));render(<CourseAccessButton courseSlug="secure-course" locale="en"/>);const button=screen.getByRole("button",{name:"Access Course"});fireEvent.click(button);fireEvent.click(button);expect(button).toBeDisabled();expect(screen.getAllByText("Preparing secure access...")).toHaveLength(2);expect(fetch).toHaveBeenCalledTimes(1);finish(success());expect(await screen.findByRole("link",{name:"Open Telegram"})).toHaveAttribute("href","https://t.me/+temporary-invite");expect(screen.getByText("Your secure Telegram invite is ready.")).toBeInTheDocument();expect(screen.getByText("This invite expires shortly.")).toBeInTheDocument()});
 it("posts only to the slug route and sends no authority fields",async()=>{vi.mocked(fetch).mockResolvedValue(success());render(<CourseAccessButton courseSlug="secure-course" locale="en"/>);fireEvent.click(screen.getByRole("button",{name:"Access Course"}));await screen.findByRole("link",{name:"Open Telegram"});expect(fetch).toHaveBeenCalledWith("/api/courses/secure-course/access",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"})});
 it("URL-encodes the slug path segment",async()=>{vi.mocked(fetch).mockResolvedValue(success());render(<CourseAccessButton courseSlug="course/unsafe" locale="en"/>);fireEvent.click(screen.getByRole("button",{name:"Access Course"}));await screen.findByRole("link",{name:"Open Telegram"});expect(fetch).toHaveBeenCalledWith("/api/courses/course%2Funsafe/access",expect.any(Object))});
 it("renders professional Arabic access states",async()=>{vi.mocked(fetch).mockResolvedValue(success());render(<CourseAccessButton courseSlug="secure-course" locale="ar"/>);fireEvent.click(screen.getByRole("button",{name:"دخول الدورة"}));expect(await screen.findByRole("link",{name:"فتح Telegram"})).toBeInTheDocument();expect(screen.getByText("رابط الدخول الآمن إلى Telegram جاهز.")).toBeInTheDocument();expect(screen.getByText("تنتهي صلاحية هذا الرابط قريباً.")).toBeInTheDocument()});
 it("shows safe unavailable and rate-limit messages",async()=>{vi.mocked(fetch).mockResolvedValueOnce(new Response(JSON.stringify({error:{code:"ACCESS_RATE_LIMITED"}}),{status:429}));render(<CourseAccessButton courseSlug="secure-course" locale="en"/>);fireEvent.click(screen.getByRole("button",{name:"Access Course"}));expect(await screen.findByText("Too many access requests. Please try again later.")).toBeInTheDocument();cleanup();vi.mocked(fetch).mockRejectedValueOnce(new Error("network"));render(<CourseAccessButton courseSlug="second-course" locale="en"/>);fireEvent.click(screen.getByRole("button",{name:"Access Course"}));await waitFor(()=>expect(screen.getByText("Course access is temporarily unavailable. Please try again shortly.")).toBeInTheDocument())});
 it("rejects an unsafe invite URL from an unexpected response",async()=>{vi.mocked(fetch).mockResolvedValue(new Response(JSON.stringify({grant:{inviteUrl:"https://attacker.test/invite"}}),{status:200}));render(<CourseAccessButton courseSlug="secure-course" locale="en"/>);fireEvent.click(screen.getByRole("button",{name:"Access Course"}));expect(await screen.findByText("Course access is temporarily unavailable. Please try again shortly.")).toBeInTheDocument();expect(screen.queryByRole("link",{name:"Open Telegram"})).not.toBeInTheDocument()});
});
