import { afterEach,describe,expect,it,vi } from "vitest";

const original={...process.env};
afterEach(()=>{for(const key of Object.keys(process.env))if(!(key in original))delete process.env[key];Object.assign(process.env,original);vi.resetModules()});
function production(values:Record<string,string>={}){Object.assign(process.env,{NODE_ENV:"production",DATABASE_URL:"postgresql://user:pass@localhost:5432/academy",APP_URL:"https://academy.example.org",JWT_SECRET:"0123456789abcdef".repeat(4),PAYMENTS_ENABLED:"false",EMAIL_ENABLED:"false",...values})}

describe("production environment validation",()=>{
 it("rejects placeholder JWT secrets",async()=>{production({JWT_SECRET:"replace-with-a-cryptographically-random-32-character-secret"});await expect(import("@/lib/env")).rejects.toThrow("JWT_SECRET must be a strong, non-placeholder secret")});
 it("fails closed when payment credentials are missing",async()=>{production({PAYMENTS_ENABLED:"true"});delete process.env.NOWPAYMENTS_API_KEY;delete process.env.NOWPAYMENTS_IPN_SECRET;delete process.env.NOWPAYMENTS_CALLBACK_URL;await expect(import("@/lib/env")).rejects.toThrow("NOWPAYMENTS_API_KEY is required")});
 it("accepts server-only payment credentials with the canonical HTTPS callback",async()=>{production({PAYMENTS_ENABLED:"true",NOWPAYMENTS_API_KEY:"live_api_key_value",NOWPAYMENTS_IPN_SECRET:"0123456789abcdef0123456789abcdef",NOWPAYMENTS_CALLBACK_URL:"https://academy.example.org/api/webhooks/payments"});const loaded=await import("@/lib/env");expect(loaded.env.PAYMENTS_ENABLED).toBe(true);expect(loaded.env.NOWPAYMENTS_API_BASE_URL).toBe("https://api.nowpayments.io/v1")});
 it("rejects a sandbox or arbitrary API endpoint in production",async()=>{production({PAYMENTS_ENABLED:"true",NOWPAYMENTS_API_KEY:"live_api_key_value",NOWPAYMENTS_IPN_SECRET:"0123456789abcdef0123456789abcdef",NOWPAYMENTS_CALLBACK_URL:"https://academy.example.org/api/webhooks/payments",NOWPAYMENTS_API_BASE_URL:"https://api-sandbox.nowpayments.io/v1"});await expect(import("@/lib/env")).rejects.toThrow("Production payments must use the production NOWPayments API");vi.resetModules();production({NOWPAYMENTS_API_BASE_URL:"https://attacker.test/v1"});await expect(import("@/lib/env")).rejects.toThrow("Invalid enum value")});
 it("requires a strong non-placeholder cron secret when configured",async()=>{production({CRON_SECRET:"short"});await expect(import("@/lib/env")).rejects.toThrow("CRON_SECRET");vi.resetModules();production({CRON_SECRET:"replace-with-a-placeholder-secret-value"});await expect(import("@/lib/env")).rejects.toThrow("CRON_SECRET must be a strong, non-placeholder secret")});
 it("requires a server-only Telegram bot token when access is enabled",async()=>{production({TELEGRAM_ACCESS_ENABLED:"true"});delete process.env.TELEGRAM_BOT_TOKEN;await expect(import("@/lib/env")).rejects.toThrow("TELEGRAM_BOT_TOKEN is required");vi.resetModules();production({TELEGRAM_ACCESS_ENABLED:"true",TELEGRAM_BOT_TOKEN:"replace-with-a-placeholder-telegram-token"});await expect(import("@/lib/env")).rejects.toThrow("valid non-placeholder bot token")});
 it("accepts a structurally valid Telegram bot token without exposing it publicly",async()=>{production({TELEGRAM_ACCESS_ENABLED:"true",TELEGRAM_BOT_TOKEN:"123456789:abcdefghijklmnopqrstuvwxyz_ABCDEF"});const loaded=await import("@/lib/env");expect(loaded.env.TELEGRAM_ACCESS_ENABLED).toBe(true);expect(process.env.NEXT_PUBLIC_TELEGRAM_BOT_TOKEN).toBeUndefined()});
});
