import { afterEach,describe,expect,it,vi } from "vitest";
import { ResendEmailProvider } from "@/lib/providers/resend-email";
import { paymentConfirmedEmail } from "@/lib/email";
afterEach(()=>vi.unstubAllGlobals());
describe("Resend email",()=>{
 it("preserves the configured sender and normalizes the recipient",async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:{id:"email-1"},error:null}),{status:200}));vi.stubGlobal("fetch",fetchMock);const provider=new ResendEmailProvider("secret","Mr.ME Trading Academy <onboarding@resend.dev>");await provider.send({to:" User@Example.com ",subject:"Verify",html:"<p>Verify</p>",text:"Verify"});const sent=JSON.parse(fetchMock.mock.calls[0][1].body);expect(sent.from).toBe("Mr.ME Trading Academy <onboarding@resend.dev>");expect(sent.to).toEqual(["user@example.com"])});
 it("rejects a successful HTTP response containing response.error",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({data:null,error:{name:"validation_error",message:"Recipient is not permitted",code:"restricted_recipient",type:"validation_error",statusCode:403}}),{status:200,headers:{"x-request-id":"request-1"}})));const provider=new ResendEmailProvider("secret","Mr.ME Trading Academy <onboarding@resend.dev>");await expect(provider.send({to:"user@example.com",subject:"Verify",html:"<p>Verify</p>",text:"Verify"})).rejects.toMatchObject({name:"ResendEmailError",safeDetails:{statusCode:403,errorName:"validation_error",errorMessage:"Recipient is not permitted",providerCode:"restricted_recipient",providerType:"validation_error",requestId:"request-1"}})});
});
describe("Payment confirmation email",()=>{it("directs the buyer to the authenticated dashboard and contains no invite",()=>{const message=paymentConfirmedEmail(["Course"]),content=`${message.text}${message.html}`;expect(content).toMatch(/protected.*dashboard/i);expect(content).not.toMatch(/https:\/\/t\.me|joinchat|invite_link/i)})});
