import { redirect } from "next/navigation";
import { getSessionUser } from "@/lib/auth";
import { isAdmin } from "@/lib/admin";
import { analyticsRange,getAdminAnalytics } from "@/lib/analytics";
import { db } from "@/lib/db";

export const metadata={title:"Sales analytics",robots:{index:false,follow:false}};
export const dynamic="force-dynamic";
export default async function Sales({searchParams}:{searchParams:Promise<{days?:string}>}){
 const actor=await getSessionUser();if(!actor)redirect("/login?next=/admin/sales");if(!isAdmin(actor))redirect("/unauthorized");
 const days=[7,30,90,365].includes(Number((await searchParams).days))?Number((await searchParams).days):30,{from,to}=analyticsRange(days),analytics=await getAdminAnalytics(from,to);
 const transactions=await db.purchase.findMany({where:{createdAt:{gte:from,lte:to}},select:{id:true,originalAmountCents:true,discountAmountCents:true,amountCents:true,currency:true,provider:true,status:true,createdAt:true,paidAt:true,user:{select:{email:true}},coupon:{select:{code:true}},items:{select:{course:{select:{titleEn:true}}}}},orderBy:{createdAt:"desc"},take:50});
 const attempts=analytics.statuses.reduce((sum,x)=>sum+x._count._all,0),paid=analytics.statuses.find(x=>x.status==="PAID")?._count._all??0;
 return <section className="container-pad pt-28 pb-24"><p className="eyebrow">Sales</p><h1 className="mt-3 text-3xl font-semibold">Confirmed sales analytics</h1><p className="mt-2 text-sm text-white/45">Revenue includes only webhook-confirmed PAID purchases and remains separated by currency.</p><div className="mt-6 flex gap-2">{[7,30,90,365].map(value=><a key={value} href={`/admin/sales?days=${value}`} className={`rounded-lg px-3 py-2 text-sm ${days===value?"bg-blue-600":"bg-white/5"}`}>{value===365?"Year":`${value} days`}</a>)}</div><div className="mt-8 grid gap-3 sm:grid-cols-4">{analytics.revenue.map(item=><Kpi key={item.currency} label={`Gross revenue (${item.currency})`} value={(item.total/100).toFixed(2)}/>)}<Kpi label="Successful orders" value={String(paid)}/><Kpi label="Conversion rate" value={attempts?`${(paid/attempts*100).toFixed(1)}%`:"0%"}/><Kpi label="Coupon redemptions" value={String(analytics.coupons)}/></div><div className="mt-10 overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-full text-sm"><thead><tr>{["Transaction","Customer","Products","Original","Discount","Final","Coupon","Status","Created","Paid"].map(x=><th key={x} className="px-4 py-3 text-start text-white/45">{x}</th>)}</tr></thead><tbody>{transactions.map(item=><tr key={item.id} className="border-t border-white/10"><td className="px-4 py-3 font-mono text-xs">{item.id}</td><td className="px-4 py-3">{item.user.email}</td><td className="px-4 py-3">{item.items.map(x=>x.course.titleEn).join(", ")}</td><td className="px-4 py-3">{(item.originalAmountCents/100).toFixed(2)} {item.currency}</td><td className="px-4 py-3">{(item.discountAmountCents/100).toFixed(2)}</td><td className="px-4 py-3">{(item.amountCents/100).toFixed(2)}</td><td className="px-4 py-3">{item.coupon?.code??"—"}</td><td className="px-4 py-3">{item.status}</td><td className="px-4 py-3">{item.createdAt.toLocaleDateString()}</td><td className="px-4 py-3">{item.paidAt?.toLocaleDateString()??"—"}</td></tr>)}</tbody></table></div></section>;
}
function Kpi({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs text-white/40">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>}
